# .github/workflows/dependabot.yml

name: Dependabot

on:
  schedule:
    # Runs every day at 2 AM
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows you to run it manually

jobs:
  dependabot:
    runs-on: ubuntu-latest
    
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Dependabot
        uses: github/dependabot-action@main
